# This will run on Travis' 'new' container-based infrastructure
sudo: true

# Blacklist
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: trade-signal-generator
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/algorithmic-problems
    - GH_REPO_REF: github.com/jaskirat1208/trade-signal-generator.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - libgtest-dev

# Build your code e.g. by calling make
script:
  - ./build.sh
  - cd build
  - make doc_doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
